### ISSUE TITLE
Token implicating not found and default index is not set

### ISSUE THREAD

**Issue by Philippekkk** [kkirchheim/pytorch-ood#22]
Hi team, when I am trying to run "pytorch-ood-dev\examples\text\newsgroups.py", but it always gives me the error:

Traceback (most recent call last):
  File "F:\lpy\chrome_download\OSDN-master\openMax\openmax.py", line 151, in <module>
    for n, batch in enumerate(loader_in_test):
  File "C:\Users\admin\.conda\envs\glenn\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Users\admin\.conda\envs\glenn\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\admin\.conda\envs\glenn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\admin\.conda\envs\glenn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\admin\.conda\envs\glenn\lib\site-packages\pytorch_ood\dataset\txt\newsgroups.py", line 124, in __getitem__
    x = self.transforms(x)
  File "F:\lpy\chrome_download\OSDN-master\openMax\openmax.py", line 76, in prep
    return torch.tensor([vocab[v] for v in tokenizer(x)], dtype=torch.int64)
  File "F:\lpy\chrome_download\OSDN-master\openMax\openmax.py", line 76, in <listcomp>
    return torch.tensor([vocab[v] for v in tokenizer(x)], dtype=torch.int64)
  File "C:\Users\admin\.conda\envs\glenn\lib\site-packages\torchtext\vocab\vocab.py", line 64, in __getitem__
    return self.vocab[token]
RuntimeError: Token implicating not found and default index is not set

Could you provide a solution? Thank you very much

**Comment by kkirchheim** [comment]
Hi, I could reproduct this. With torchtext `0.14.0`, it seems that we now have to set a default token using `set_default_index`.

**Comment by kkirchheim** [comment]
Should be fixed with the new release v0.1.5

**Comment by Philippekkk** [comment]
Could you please tell me the versions of python packages which you are using,such as "python"、"torch"、"torchaudio"、"torchtext"、"torchdata"、"torchvision"、"pytorch-ood"?

Thank you very much

**Comment by kkirchheim** [comment]
My current (anaconda) environment uses Python 3.9.15 

All packages with torch:
```
pytorch=1.13.0=py3.9_cuda11.7_cudnn8.5.0_0
pytorch-cuda=11.7=h778d358_5
pytorch-mutex=1.0=cuda
torchaudio=0.13.0=py39_cu117
torchtext=0.14.0=py39
torchtriton=2.0.0=py39
efficientnet-pytorch==0.7.1
segmentation-models-pytorch==0.3.2
torchmetrics==1.0.1
torchvision==0.15.2
```

Setup with 
```
 conda install pytorch torchvision torchaudio torchtext==0.14.0 pytorch-cuda=11.7 -c pytorch -c nvidia
```
I usually work on the current `dev` branch of `pytorch-ood`.
